### ISSUE TITLE
Add border radius to all containers

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#10]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

Add some border radius to all containers i.e. "Name", "Roll No", "Hobby", and "Describe in one word".

**Comment by Harshs0891** [comment]
Sir, i want to work on this issue, could you please assign me this, thanks

**Comment by superiorsd10** [comment]
@Harshs0891 First resolve the issue already assigned to you. Once you're done with it, I'll assign this one to you.

**Comment by Harshs0891** [comment]
sir ,Plz Assign me this issue,I wants to work on it

**Comment by Harshs0891** [comment]
i have completed the assigned issues

**Comment by superiorsd10** [comment]
@Harshs0891 Okay, I'm assigning this to you! All the best! Start from a new branch.
