### ISSUE TITLE
Remove shadow from flutter text

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#11]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

On the bottom part of the screen, a blue shadow is visible with the "Flutter ❤️" text. Remove that shadow.

**Comment by Zhu-VISH** [comment]
Hi @superiorsd10 I would like to work on this issue, please assign it to me.

**Comment by superiorsd10** [comment]
Good to see your enthusiasm @Zhu-VISH but first complete the issue already assigned to you. After your PR for the previous issue is merged, I'll assign you this one.

**Comment by Zhu-VISH** [comment]
@superiorsd10 Sure

**Comment by superiorsd10** [comment]
@Zhu-VISH I'm assigning it to you. Now you can work on it. Also, make a different branch for different issues.
