### ISSUE TITLE
Remove the floating action button

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#12]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

Remove the unnecessary floating action button center docked at the bottom of the screen.

**Comment by Harshs0891** [comment]
Sir Plz assign me this issue i wants to work on it .. i have completed my previous assigned issues

**Comment by superiorsd10** [comment]
Okay @Harshs0891 ! I'm assigning this to you! All the best!
