### ISSUE TITLE
Add your introduce yourself app

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#2]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

Make an introduce yourself app, and add the `main.dart` file in the `lib/introduce_yourself_apps` directory. Rename the `main.dart` file to `your_name.dart` file. Add the images in the `assets` folder and custom fonts in the `fonts` folder.

**Comment by Dis1309** [comment]
ss of introduce yourself
![ss of photo](https://user-images.githubusercontent.com/119830584/216808013-2f9aa7b7-6a3d-4df6-b9c4-236ef02cc178.PNG)

**Comment by superiorsd10** [comment]
@Dis1309 Looks good! Thanks for adding the screenshots of the app. I'm giving points to you now. 
`accepted-12` - (10 for hard issue + 2 for creativity)
