### ISSUE TITLE
Remove the debug banner

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#3]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

Remove the debug banner visible at the top right corner of the screen.

**Comment by Dis1309** [comment]
hi @superiorsd10 I would like to work on this issue ,please assign it to me

**Comment by superiorsd10** [comment]
Sure @Dis1309 ! All the best!
