### ISSUE TITLE
Background image is not covering the entire screen

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#4]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

As you can see that the background image is not covering the entire screen, and the background color i.e. white is visible on the screen. So you've to make the background image cover the entire screen below the app bar.

**Comment by Dis1309** [comment]
hi @superiorsd10 I would like to work on this issue ,please assign it to me

**Comment by superiorsd10** [comment]
Sure @Dis1309 ! All the best!
