### ISSUE TITLE
Screen content is appearing on left instead of centre

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#5]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

You've to center the content i.e. widgets on the introduce yourself screen horizontally. It's appearing on the left now.

**Comment by Dis1309** [comment]
hi @superiorsd10 I would like to work on this issue ,please assign it to me

**Comment by superiorsd10** [comment]
Sure @Dis1309 ! As I've mentioned in your last PR, you should make separate PRs for separate issues you're working on, so take care of it from now onwards. I'm assigning it to you.
