### ISSUE TITLE
Circle avatar is looking smaller

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#6]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

The circle avatar looks too smaller right now. So you'll have to increase its size so that it becomes clearly visible.

**Comment by Zhu-VISH** [comment]
Hi @superiorsd10 I would like to work on this issue, please assign it to me.

**Comment by superiorsd10** [comment]
@Zhu-VISH First make a PR to this issue #9 , after that I'll assign you this.
