### ISSUE TITLE
Name container's border is not visible

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#7]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

The border around the name container is not visible. Make necessary changes in the code so that it becomes visible.

**Comment by Harshs0891** [comment]
"hey, i want to work on this issue, could you please assign me this, thanks."

**Comment by Harshs0891** [comment]
"Sir, i want to work on this issue, could you please assign me this, thanks."

**Comment by superiorsd10** [comment]
Sure @Harshs0891 ! All the best! Make a new branch from the main, and then start working on this issue.
