### ISSUE TITLE
Bad formatting of text in roll no. container

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#8]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

There is no even space between the text and container in the three texts of roll no. container. Format it properly like other containers.

**Comment by Harshs0891** [comment]
Sir, i want to work on this issue, could you please assign me this, thanks.

**Comment by superiorsd10** [comment]
@Harshs0891 First resolve the issue already assigned to you. Once you're done with it, I'll assign this one to you.

**Comment by superiorsd10** [comment]
Do you want to work on this issue now? @Harshs0891

**Comment by Harshs0891** [comment]
Yes sir

**Comment by Harshs0891** [comment]
plz assign this issue to me

**Comment by superiorsd10** [comment]
@Harshs0891 Okay, I'm assigning it to you!
