### ISSUE TITLE
Red text colour in writing text instead of white

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/introduce-yourself-app#9]
Read the [contribution guidelines](https://github.com/iiitl/introduce-yourself-app/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/introduce-yourself-app/blob/main/README.md). Ask to get assigned this issue.

### Description

In the hobby container, the "Writing" text is appearing red instead of white. Make proper changes in the code to tackle this issue.

**Comment by Zhu-VISH** [comment]
Hi @superiorsd10 I would like to work on this issue, please assign it to me.

**Comment by superiorsd10** [comment]
Sure **@Zhu-VISH** I'm assigning it to you! All the best!

**Comment by superiorsd10** [comment]
@Zhu-VISH you haven't made PR to resolve this issue!
